// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGj5M3CHTN6UTLtJLdggFJ7EjAOK5u_s',
    appId: '1:834954121727:android:845862e8f6c7bc8b26d7ca',
    messagingSenderId: '834954121727',
    projectId: 'dssfirebaseproject-3c758',
    databaseURL: 'https://dssfirebaseproject-3c758.firebaseio.com',
    storageBucket: 'dssfirebaseproject-3c758.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0GeW-3Y4R02HZNjvNQg-ZSb8O68sqC6M',
    appId: '1:834954121727:ios:c8a26721a07282aa26d7ca',
    messagingSenderId: '834954121727',
    projectId: 'dssfirebaseproject-3c758',
    databaseURL: 'https://dssfirebaseproject-3c758.firebaseio.com',
    storageBucket: 'dssfirebaseproject-3c758.appspot.com',
    androidClientId: '834954121727-gkbtq29hktptbamqeq75v6nd5c66247j.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareBill',
  );
}
